### ISSUE TITLE
Проверить ДЗ

### ISSUE THREAD

**Issue by bertRC** [bertRC/web-app#1]

**Comment by coursar** [comment]
Всё ок

**Comment by coursar** [comment]
Но лучше было заранее в JdbcTemplate предусмотреть возврат авто-сгенерированного id.

**Comment by bertRC** [comment]
Да, я пока не до конца разобрался как это работает. В следующей домашке сделаю

**Comment by bertRC** [comment]
У меня возникло небольшое заблуждение по поводу возврата авто-сгенерированного id.

На лекции 12 (суббота, 09.11.2019) мы разбирали пример JdbcTemplate. Как я понимаю, для возврата авто-сгенерированного ключа надо использовать метод `executeUpdateWithGeneratedKey` из примера (/Lection12/x01. Interfaces/.../util/JdbcTemplate.java):
```
  public int executeUpdateWithGeneratedKey(
      String url,
      String sql,
      PreparedStatementSetter preparedStatementSetter
  ) {
    try (
        Connection connection = DriverManager.getConnection(url);
        PreparedStatement statement = connection.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);
    ) {

      preparedStatementSetter
          .setValues(statement)
          .executeUpdate();

      try (ResultSet generatedKeys = statement.getGeneratedKeys();) {
        if (generatedKeys.next()) {
          return generatedKeys.getInt(1);
        }

        throw new NoGeneratedKeysException();
      }
    } catch (SQLException e) {
      e.printStackTrace();
      throw new DataStoreException(e);
    }
  }
```

Однако в том же примере у репозитория `BurgerRepositoryJdbcImpl` как-то странно реализован метод `create`:
```
  @Override
  public Burger create(Burger burger) {
    String sql = "INSERT INTO burgers (name, price) VALUES (?, ?);";
    int id = jdbcTemplate.executeUpdate(url, sql, stmt -> {
      stmt.setString(1, burger.getName());
      stmt.setInt(2, burger.getPrice());
      return stmt;
    });
    burger.setId(id);
    return burger;
  }
```
Я имею ввиду, что в данном случае странным кажется то какое значение кладётся в переменную `id`. Туда присваивается значение типа `int` метода `executeUpdate` от `PreparedStatement`. Но ведь он возвращает не то что нам нужно, это не имеет никакого отношения к нашему авто-сгенерированному базой данных `id`.

Это какая-то ошибка?

**Comment by coursar** [comment]
Да, должен вызываться `executeUpdateWithGeneratedKey`, поправлю
